### ISSUE TITLE
conduct market research

### ISSUE THREAD

**Issue by afeld** [uscensusbureau/fismatic#12]
We believe that other agencies/organizations have likely done work similar/related to FISMAtic - let's see what else is out there.

[Spreadsheet for tracking](https://uscensus.sharepoint.com/:x:/r/sites/xd/_layouts/15/Doc.aspx?sourcedoc={29ded4a5-cad6-4c4d-891a-ce1c9461f5cb}&action=editnew) (internal only). Lots of overlap with #9.

**Comment by trevorbryant** [comment]
I've reached out to former colleagues of mine and they are interested in the outreach.

If you could add Kara Jackson and Francois Le. I'll get you in touch with them.

**Comment by afeld** [comment]
Merging into #9.
