### ISSUE TITLE
read the 10x Automating Continuous Compliance report

### ISSUE THREAD

**Issue by afeld** [uscensusbureau/fismatic#13]
https://docs.google.com/document/d/16wszsijG5wmRSw1pGWP9HX5C0k9P_iJg2DFzycE_g7g/edit

**Comment by afeld** [comment]
@Jkrzy @wslack When you wrote

> The highest-value area for continued work is exploration of automation approaches to facilitate more efficient ongoing monitoring and auditing of an ATO’d system.

did you mean "...relative to work on improving the documentation workflows", or was the focus only on the assessment/testing step?

**Comment by afeld** [comment]
Closing this as I have now read it, but we can continue the discussion regardless.

**Comment by wslack** [comment]
I think it was thinking specifically about recurring automated tasks (given that the doc workflows aren't so automatable), but I don't have a copy of it avail on this computer.

I don't think we were specifically comparing what Compliance Masonry does, for example.
